### ISSUE TITLE
Expire not working

### ISSUE THREAD

**Issue by mcbalint011hun** [hxr404/Discord-ExpireBot#11]
I installed the bot, its working perfectly, the only thing it doesn't do, is its job. I set an expire to my role, then give it to someone, but it never expires. I double checked, and the role is set to expire in 10 seconds, but it doesn't. I just normally give the role to someone, and it doesn't expire. I just need to give the role to someone normally, right? Actually the role has a non english "é" letter in it, because im hungarian, could that be the problem?

**Comment by mcbalint011hun** [comment]
I tried with a role that has only english letters in it, it doesn't work either.

**Comment by hxr404** [comment]
Is the Bot's role higher than the Role you want to expire?
And maybe try giving the Bot admin perms, this can also fix some problems.
Non-english letters shouldn't cause problems, as the bot works with the Role's ID and not names.

> I just need to give the role to someone normally, right?
exactly. The Bot should detect every possible way of giving a Role (Even when other Bots assign them)

**Comment by mcbalint011hun** [comment]
Yes, the role was not higher, that was causing the problem. Thanks for the help!

**Comment by hxr404** [comment]
Ok no problem. Glad I could help
