### ISSUE TITLE
Error while starting - multiple VPS same issue

### ISSUE THREAD

**Issue by wrathfuldev** [hxr404/Discord-ExpireBot#12]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    bot = Bot(command_prefix=command_prefix, intents=discord.Intents.all(), help_command=None)
AttributeError: module 'discord' has no attribute 'Intents'

**Comment by hxr404** [comment]
Did you enable all Intents for the Bot (at discord.com/developers) ?

**Comment by hxr404** [comment]
Closed due to no response
