### ISSUE TITLE
HTTPException: 429 Too Many Requests

### ISSUE THREAD

**Issue by IsmaStifler** [hxr404/Discord-ExpireBot#13]
HTTPException: 429 Too Many Requests (error code: 0): You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward.

**Comment by IsmaStifler** [comment]
> HTTPException: 429 Too Many Requests (error code: 0): You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward.

any idea?

**Comment by hxr404** [comment]
well, you kinda ended up getting your Bot rate-limited...
For bot accounts this is max. 50 requests per second. Your Bot should be unblocked again after some waiting.
if this doesn't work, you probably exceeded the global limit of 10000 requests per 10 minutes, which would result in your IP getting temporarily banned. This should also "fix itself" after some waiting.

**Comment by hxr404** [comment]
If you still have problems feel free to reopen.
